---
classoption: landscape
output:  
  pdf_document:
    fig_caption: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE, warning=FALSE, include=FALSE}
library(knitr)
library(tinytex)
library(ggplot2)
library(dplyr)
library(tidyr)
library(kableExtra)

```


```{r, include=FALSE}
#options(kableExtra.auto_format = FALSE)
options(tinytex.verbose = TRUE)
```

```{r, echo=FALSE, warning=FALSE, include=FALSE}
SurveyTable = read.csv("SurveyTable.csv") %>%
  rename("Gear Method" = Gear.Method,
         "Gear Type" = Gear.Type,
         "Sample Area" = Sample.Area,
         "Sample Interval" = Sample.Interval,
         "Sample Method" = Sample.Method,
         "N(events)" = N.events.,
         "CPUE Standardization" = CPUE.Standardization) 

SurveyClass = read.csv("SurveyClass.csv") %>%
  rename("Total CPUE" = Total.CPUE,
         "Immature Female" = Immature.Female,
         "Mature Female" = Mature.Female,
         "Immature Male" = Immature.Male,
         "Mature Male" = Mature.Male) 

```

```{r Survey Background, include=TRUE, echo=FALSE, warning=FALSE, include=TRUE, fig.cap="Table 1: SCDNR fisheries independent survey methodology"}
Ch1_Table = kable(SurveyTable, "latex", booktabs = T) %>%
  kable_styling(latex_options = "scale_down" , font_size = 8) %>%
  add_header_above(c(" " = 1, "Gear" = 2, "Sample" = 3, "Data" = 2)) %>%
  pack_rows("CRMS", 1,3) %>%
  pack_rows("ERS", 4,5) %>%
  pack_rows("IFRS", 6,6) %>%
  column_spec(7, width = "5em") %>%
  column_spec(3:6, width = "6em") %>%
  column_spec(8, width = "7em")

Ch1_Table

```
Table 1: SCDNR fisheries independent survey methodology
\newpage

```{r Survey Data, include=TRUE, echo=FALSE, warning=FALSE, include=TRUE, fig.cap="Table 2: Lifestage data for blue crab by SCDNR fisheries independent survey"}
Ch1_SurveyLifestageTable = kable(SurveyClass, "latex", booktabs = T, align = "lcccccccccc") %>%
  kable_styling(latex_options = "scale_down" , font_size = 8) %>%
  add_header_above(c(" " = 2, "Size" = 3, "Legal (Size)" = 2, "Class (Sex/Maturity)" = 4)) %>%
  pack_rows("CRMS", 1,3) %>%
  pack_rows("ERS", 4,5) %>%
  pack_rows("IFRS", 6,6) 

Ch1_SurveyLifestageTable

```
Table 2: Lifestage data for blue crab by SCDNR fisheries independent survey