---
title: "Predicting blue crab abundance and landings from fisheries independent surveys in Charleston Harbor, South Carolina"
output:
  pdf_document: default
  word_document: default
editor_options: 
  chunk_output_type: inline
---


```{r knitr setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r setup, include=FALSE, echo=FALSE}
library(ggplot2)
library(lubridate)
library(tidyr)
library(dplyr)
library(Hmisc)
library(nlme)
library(cowplot)
library(gridExtra)
library(ggpmisc)

theme_set(theme_classic(base_size = 12)+
            theme(panel.grid.major = element_blank(), 
                  panel.grid.minor = element_blank(),
                  panel.background = element_rect(colour = "black", size=0.5))+
            theme(text=element_text(size=12,  family="serif", colour = "black"))+
            theme(axis.text = element_text(colour = "black"))+
            theme(axis.ticks = element_line(colour = "black"))
)
update_geom_defaults("point",   list(colour = "black"))
update_geom_defaults("line",   list(colour = "black"))
theme_update(plot.title = element_text(hjust = 0.5))
```

```{r Data Read-In, include=FALSE, warning=FALSE, message=FALSE}

crabdata <- read.csv("ClassSizeAbunDistinct_201912.csv", stringsAsFactors = FALSE)


#Source - Eric Hiltz OFM Fisheries Statistics
#Wrangled in Excel due to confidentiality
depend <- read.csv("MonthlyDependent.csv")
```

```{r Data Wrangling, include=FALSE, warning=FALSE, message=FALSE}
B90T38 = crabdata %>% #Formerly crab1
  select(1:4, 7:16) %>%
  filter(ProjID %in% c("B90", "T38")) %>%
  rename(Total = CPUE,
         Juvenile = JuvCPUE,
         Subadult = SubadultCPUE,
         Adult = AdultCPUE,
         "Immature Female" = ImmatureFemaleCPUE,
         "Mature Female" = MatureFemaleCPUE,
         "Immature Male" = ImmatureMaleCPUE,
         "Mature Male" = MatureMaleCPUE,
         Sublegal = SublegalCPUE,
         Legal = LegalCPUE) %>%
  gather("Lifestage", "CPUE", 5:14) %>%
  mutate(Year = year(StartTime)) %>%
  mutate(Month = month(StartTime)) %>%
  select(1,2,4,3,7,8,5,6) 

T06 = crabdata %>% #Formerly crab1
  select(1:4, 7:16) %>%
  filter(ProjID %in% "T06") %>%
  rename(Total = CPUE) %>%
  select(1:5) %>%
  gather("Lifestage", "CPUE", 5) %>%
  mutate(Year = year(StartTime)) %>%
  mutate(Month = month(StartTime)) %>%
  select(1,2,4,3,7,8,5,6) 


P88 = crabdata %>% #Formerly crab1
  select(1:4, 7:16) %>%
  filter(ProjID %in% "P88") %>%
  rename(Total = CPUE,
         Sublegal = SublegalCPUE,
         Legal = LegalCPUE) %>%
  distinct(Coll, .keep_all = TRUE) %>%
  select(1:5, 13, 14) %>%
  gather("Lifestage", "CPUE", 5:7) %>%
  mutate(Year = year(StartTime)) %>%
  mutate(Month = month(StartTime)) %>%
  select(1,2,4,3,7,8,5,6) 

p88Crab = crabdata %>% #Formerly crab1
  select(1:4, 7:16) %>%
  filter(ProjID %in% "P88") 


SCECAP = crabdata %>% #Formerly crab1
  select(1:4, 7:16) %>%
  filter(ProjID %in% c("E98", "E99")) %>%
  rename(Total = CPUE,
         Sublegal = SublegalCPUE,
         Legal = LegalCPUE,
         Juvenile = JuvCPUE,
         Subadult = SubadultCPUE,
         Adult = AdultCPUE) %>%
  select(1:8, 13, 14) %>%
  gather("Lifestage", "CPUE", 5:10) %>%
  mutate(Year = year(StartTime)) %>%
  mutate(Month = month(StartTime)) %>%
  select(1,2,4,3,7,8,5,6) 

crab1 = rbind(B90T38, P88) %>%
  rbind(., T06) %>%
  rbind(., SCECAP)



#Source - Eric Hiltz OFM Fisheries Statistics
#Wrangled in Excel due to confidentiality
depend <- read.csv("MonthlyDependent.csv")


#Joining Independent and Dependent 
crab3 = full_join(crab1, depend,
                  by = c("ProjID", "StationCode", "Year", 
                         "Month", "Lifestage", "CPUE")) %>%
  mutate(ProjID = as.factor(ProjID)) %>%
  mutate(Coll = as.factor(Coll)) %>%
  mutate(StationCode = as.factor(StationCode)) %>%
  mutate(StartTime = ymd(StartTime)) %>%
  mutate(Year = as.numeric(Year)) %>%
  mutate(Month = as.factor(Month)) %>%
  mutate(Lifestage = as.factor(Lifestage)) %>%
  group_by(ProjID, StationCode, Lifestage, Month) %>%
  mutate(Means = mean(CPUE, na.rm=TRUE),
         SDs = sd(CPUE, na.rm=TRUE),
         Zs = (CPUE-Means)/ifelse(SDs>0,SDs, 0.00000001)) %>%
  ungroup() 

#### IS.FINITE NEEDS TO GO HERE FOR mATURE fEMALE STAT_SUMMS AND GEOM_HLINES

crab = crab3 %>%
  mutate(ProjID = recode(ProjID, 'B90' = "Harbor Trawl",
                         'T38' = "Creek Trawl",
                         'T06' = "Trammel Net",
                         'P88' = "Ashley Potting",
                         'E98' = "SCECAP Creek Trawl",
                         'E99' = "SCECAP Harbor Trawl"))


```

```{r Figure 1, echo=FALSE, message=FALSE, warning=FALSE,dpi=600, fig.cap="(A) Total annual blue crab Landings (mean ± standard error), and (B) mean annual landings CPUE (mean ± standard error) for all reporting areas within the Charleston Harbor watershed (Ashley River, Wando River, Cooper River and Charleston Harbor)", fig.width=10,fig.height=11}
LandingsCPUEFormTotal = subset(crab,
                           ProjID == "LandingsCPUEMean")

formula1 <- lm(LandingsCPUEFormTotal$CPUE ~ LandingsCPUEFormTotal$Year)

LandingsCrab = crab %>%
  filter(ProjID == c("LandingsSum", "LandingsCPUEMean")) %>%
  group_by(ProjID) %>%
  mutate(Means = mean(CPUE, na.rm=TRUE),
         SDs = sd(CPUE, na.rm=TRUE),
         Zs = (CPUE-Means)/ifelse(SDs>0,SDs, 0.00000001)) %>%
  ungroup() 


LandingsCPUE = ggplot(aes(Year, CPUE), data = subset(LandingsCrab,
                                                     ProjID == "LandingsCPUEMean")) +
  ggtitle("Mean Annual Landings CPUE\nCharleston Harbor (Combined Watersheds)") +
  geom_hline(aes(yintercept=mean(CPUE)), linetype="dashed") +
  stat_summary(fun.data = "mean_se", size = .7) +
  stat_poly_eq(aes(label = ..eq.label..), formula = formula1, parse = TRUE) +
  geom_smooth(method = 'loess', se=FALSE, color="black") +
  labs(y=expression(Blue~crab~~per~pot~fished^{-1})) +
  expand_limits(x=c(1980, 2022)) 




LandingsFormTotal = subset(crab,
                      ProjID == "LandingsSum")
formula2 <- lm(LandingsFormTotal$CPUE ~ LandingsFormTotal$Year)
Landings = ggplot(aes(Year, CPUE), data = subset(LandingsCrab,
                                                 ProjID == "LandingsSum")) +
  ggtitle("Total Annual Landings\nCharleston Harbor (Combined Watersheds)") +
  geom_hline(aes(yintercept=mean(CPUE)), linetype="dashed") +
  stat_summary(fun.data = "mean_se", size = .7) +
  stat_poly_eq(aes(label = ..eq.label..), formula = formula2, parse = TRUE) +
  geom_smooth(method = 'loess', se=FALSE, color="black") +
  labs(y=expression(Blue~crab~lbs.~per~year^{-1})) +
  expand_limits(x=c(1980, 2022)) 



LandingsFormTotal04 = subset(crab,
                      ProjID == "LandingsSum" &
                        Year > 2002)
formula3 <- lm(LandingsFormTotal04$CPUE ~ LandingsFormTotal04$Year)
Landings04 = ggplot(aes(Year, CPUE), data = subset(LandingsCrab,
                                                 ProjID == "LandingsSum" &
                                                   Year > 2002)) +
  ggtitle("Total Annual Landings\nCharleston Harbor (Combined Watersheds)") +
  geom_hline(aes(yintercept=mean(CPUE)), linetype="dashed") +
  stat_summary(fun.data = "mean_se", size = .7) +
  stat_poly_eq(aes(label = ..eq.label..), formula = formula3, parse = TRUE) +
  geom_smooth(method = 'loess', se=FALSE, color="black") +
  labs(y=expression(Blue~crab~lbs.~per~year^{-1})) +
  expand_limits(x=c(1980, 2022)) 
  


LandingsTimeSeries <- plot_grid(Landings, LandingsCPUE, ncol = 1, align = 'hv', labels = c("A", "B"))

  LandingsTimeSeries

```

```{r B90 Size Wrangle, include=FALSE, warning=FALSE, message=FALSE}
TotalCrab = crab %>%
  filter(Lifestage == "Total")
TotalCrab$ProjID <- factor(TotalCrab$ProjID, levels = c("Harbor Trawl",
                                                        "SCECAP Harbor Trawl",
                                                        "Creek Trawl",
                                                        "SCECAP Creek Trawl",
                                                        "Trammel Net",
                                                        "Ashley Potting"))

B90FormTotal = subset(TotalCrab,
                     ProjID == "Harbor Trawl")
formula3 <- lm(B90FormTotal$CPUE ~ B90FormTotal$Year)
B90TotalCPUE = ggplot(aes(Year, CPUE), data = subset(TotalCrab,
                                                     ProjID == "Harbor Trawl")) +
  ggtitle(" ") +
  #ggtitle("Harbor Trawl") + 
  stat_summary(fun.data = "mean_se", size = .7) +
  #stat_poly_eq(aes(label = ..eq.label..), formula = formula3, parse = TRUE) +
  geom_smooth(method = 'loess', se=FALSE, color="black") +
  geom_hline(aes(yintercept=mean(Means)), linetype="dashed") +
  labs(y=expression(" "), x=expression(" ")) +
  #labs(y=expression(Blue~crab~per~tow^{-1})) +
  expand_limits(x=2020)
#B90TotalCPUE

T38FormTotal = subset(TotalCrab,
                     ProjID == "Creek Trawl")
formula4 <- lm(T38FormTotal$CPUE ~ T38FormTotal$Year)
T38TotalCPUE = ggplot(aes(Year, CPUE), data = subset(TotalCrab,
                                                     ProjID == "Creek Trawl")) +
  ggtitle(" ") +
    #ggtitle("Creek Trawl") +
  stat_summary(fun.data = "mean_se", size = .7) +
  #stat_poly_eq(aes(label = ..eq.label..), formula = formula4, parse = TRUE, label.x = "right") +
  geom_smooth(method = 'loess', se=FALSE, color="black") +
  geom_hline(aes(yintercept=mean(Means)), linetype="dashed") +
  labs(y=expression(" "), x=expression(" ")) +
  #labs(y=expression(Blue~crab~per~tow^{-1})) +
  expand_limits(x=2020)
#T38TotalCPUE

T06FormTotal = subset(TotalCrab,
                     ProjID == "Trammel Net")
formula5 <- lm(T06FormTotal$CPUE ~ T06FormTotal$Year)
T06TotalCPUE = ggplot(aes(Year, CPUE), data = subset(TotalCrab,
                                                     ProjID == "Trammel Net")) +
  ggtitle(" ") +
  #ggtitle("Trammel Net") +
  stat_summary(fun.data = "mean_se", size = .7) +
  #stat_poly_eq(aes(label = ..eq.label..), formula = formula5, parse = TRUE) +
  geom_smooth(method = 'loess', se=FALSE, color="black") +
  labs(y=expression(" "), x=expression(" ")) +
  geom_hline(aes(yintercept=mean(Means)), linetype="dashed") +
  #labs(y=expression(Blue~crab~per~set^{-1})) +
  expand_limits(x=c(1980,2020))
#T06TotalCPUE

E98FormTotal = subset(TotalCrab,
                     ProjID == "SCECAP Creek Trawl")
formula6 <- lm(E98FormTotal$CPUE ~ E98FormTotal$Year)
E98TotalCPUE = ggplot(aes(Year, log(CPUE)), data = subset(TotalCrab,
                                                          ProjID == "SCECAP Creek Trawl")) +
  ggtitle(" ") +
  #ggtitle("SCECAP Tidal Creek Trawl") +
  stat_summary(fun.data = "mean_se", size = .7) +
  #stat_poly_eq(aes(label = ..eq.label..), formula = formula6, parse = TRUE) +
  geom_smooth(method = 'loess', se=FALSE, color="black") +
  geom_hline(aes(yintercept=(log(mean(Means)))), linetype="dashed") +
  labs(y=expression(" "), x=expression(" ")) +
  #labs(y=expression((log)~Blue~crab~per~tow^{-1})) +
  expand_limits(x=c(1980,2020)) +
  coord_cartesian(ylim = c(0,8))

E99FormTotal = subset(TotalCrab,
                     ProjID == "SCECAP Harbor Trawl")
formula7 <- lm(E99FormTotal$CPUE ~ E99FormTotal$Year)
E99TotalCPUE = ggplot(aes(Year, CPUE), data = subset(TotalCrab,
                                                     ProjID == "SCECAP Harbor Trawl")) +
  ggtitle(" ") +
  #ggtitle("SCECAP Open Water Trawl") +
  stat_summary(fun.data = "mean_se", size = .7) +
  #stat_poly_eq(aes(label = ..eq.label..), formula = formula7, parse = TRUE) +
  geom_smooth(method = 'loess', se=FALSE, color="black") +
  geom_hline(aes(yintercept=mean(Means)), linetype="dashed") +
  labs(y=expression(" "), x=expression(" ")) +
  #labs(y=expression(Blue~crab~per~tow^{-1})) +
  expand_limits(x=c(1980,2020)) 

P88FormTotal = subset(TotalCrab,
                     ProjID == "Ashley Potting")
formula8<- lm(P88FormTotal$CPUE ~ P88FormTotal$Year)
P88FallTotalCPUE = TotalCrab %>%
  filter(ProjID == "Ashley Potting") %>%
  filter(Month %in% c("10", "11"))
P88FallTotalCPUE = ggplot(aes(Year, CPUE), data = subset(TotalCrab,
                                                         ProjID == "Ashley Potting")) +
  ggtitle(" ") +
  #ggtitle("Ashley River Potting Survey (fall)") +
  stat_summary(fun.data = "mean_se", size = .7) +
  #stat_poly_eq(aes(label = ..eq.label..), formula = formula8, parse = TRUE) +
  geom_smooth(method = 'loess', se=FALSE, color="black", na.rm = TRUE) +
  geom_hline(aes(yintercept=mean(Means)), linetype="dashed") +
  labs(y=expression(" "), x=expression(" ")) +
  #labs(y=expression(Blue~crab~per~soak^{-1})) +
  expand_limits(x=c(1980,2020))


##Only going to use this if we need a year-round look, but only goes to 2003
P88FormTotal2 = subset(TotalCrab,
                      ProjID == "Ashley Potting" &
                        Year > 2002)
formula9 <- lm(P88FormTotal$CPUE ~ P88FormTotal$Year)
P88TotalAnnualCPUE = ggplot(aes(Year, CPUE), data = subset(TotalCrab,
                                                           ProjID == "Ashley Potting" &
                                                             Year > 2002)) +
  ggtitle(" ") +
  #ggtitle("Ashley River Potting Survey (bi-monthly)") +
  stat_summary(fun.data = "mean_se", size = .7) +
  #stat_poly_eq(aes(label = ..eq.label..), formula = formula9, parse = TRUE) +
  geom_smooth(method = 'loess', se=FALSE, color="black", na.rm = TRUE) +
  geom_hline(aes(yintercept=mean(Means)), linetype="dashed") +
  labs(y=expression(" "), x=expression(" ")) +
  #labs(y=expression(Blue~crab~per~soak^{-1})) +
  expand_limits(x=c(1980,2020))
```

```{r Figure 2 (CRMS Survey Time Series), echo=FALSE, message=FALSE, warning=FALSE,dpi=600, fig.cap="Mean annual blue crab (total catch) CPUE (mean ± standard error) for all SCDNR Crustacean Section fisheries independent surveys, including Harbor Trawl (A), Creek Trawl (B), and Ashley River Potting Survey (C), SCECAP Open Water Trawl (D), SCECAP Tidal Creek Trawl (E), and the Inshore Fisheries Trammel Net survey (F).", fig.width=10,fig.height=11}

CRMSCPUETimeSeries <- plot_grid(B90TotalCPUE, T38TotalCPUE, P88FallTotalCPUE, 
                                E99TotalCPUE, E98TotalCPUE, T06TotalCPUE, ncol = 2, align = 'hv',
                                labels = c("A", "B", "C", "D", "E", "F")) 
  
CRMSCPUETimeSeries

```

##########NEED TO FIX LABELS ON FIGURE 2##########

