---
title: "Chapter 1 - Index of Abundance"
output:
  pdf_document: default
  word_document: default
editor_options: 
  chunk_output_type: inline
---


```{r setup, include=FALSE, echo=FALSE}
library(ggplot2)
library(lubridate)
library(tidyr)
library(dplyr)
library(Hmisc)
library(nlme)
library(cowplot)
library(gridExtra)
library(ggpmisc)

theme_set(theme_classic(base_size = 12)+
            theme(panel.grid.major = element_blank(), 
                  panel.grid.minor = element_blank(),
                  panel.background = element_rect(colour = "black", size=0.5))+
            theme(text=element_text(size=12,  family="serif", colour = "black"))+
            theme(axis.text = element_text(colour = "black"))+
            theme(axis.ticks = element_line(colour = "black"))
)
update_geom_defaults("point",   list(colour = "black"))
update_geom_defaults("line",   list(colour = "black"))
theme_update(plot.title = element_text(hjust = 0.5))
```

```{r Data Read-In, include=FALSE, warning=FALSE, message=FALSE}
#Source crab.R, flatfile/cleandata/MeanAnnualVars3.csv
crabdata <- read.csv("MeanAnnualVars3.csv", stringsAsFactors = FALSE)

#Source - Eric Hiltz OFM Fisheries Statistics
#Wrangled in Excel due to confidentiality
depend <- read.csv("dependent.csv") %>%
  select(1, 6, 12) %>%
  rename(Landings = SumLandings,
         LandingsCPUE = SumCPUE)

```


```{r Independent Data Wrangling, include=FALSE, warning=FALSE, message=FALSE}
B90T38 = crabdata %>%
  filter(ProjID %in% c("B90", "T38")) %>%
  select(1:2, 5:14) %>%
  rename(Total = CPUE,
         Juvenile = JuvCPUE,
         Subadult = SubadultCPUE,
         Adult = AdultCPUE,
         ImmatureFemale = ImmatureFemaleCPUE,
         MatureFemale = MatureFemaleCPUE,
         ImmatureMale = ImmatureMaleCPUE,
         MatureMale = MatureMaleCPUE,
         Sublegal = SublegalCPUE,
         Legal = LegalCPUE) #%>%
  #gather("Lifestage", "CPUE", 3:12) 

B90 = B90T38 %>%
  filter(ProjID %in% "B90") %>%
  left_join(.,depend, by = "Year")

T38 = B90T38 %>%
  filter(ProjID %in% "T38") %>%
  left_join(.,depend, by = "Year")

T06 = crabdata %>% 
  select(1:2, 5:14) %>%
  filter(ProjID %in% "T06") %>%
  rename(Total = CPUE) %>%
  select(1:3) %>%
  left_join(.,depend, by = "Year")#%>%
  #gather("Lifestage", "CPUE", 3)  


P88 = crabdata %>% 
  select(1:2, 5:14) %>%
  filter(ProjID %in% "P88") %>%
  rename(Total = CPUE,
         Sublegal = SublegalCPUE,
         Legal = LegalCPUE) %>%
  select(1:3, 11:12) %>%
  left_join(.,depend, by = "Year")#%>%
  #gather("Lifestage", "CPUE", 3:5) 


E99 = crabdata %>% 
  select(1:2, 5:14) %>%
  filter(ProjID %in% "E99") %>%
  rename(Total = CPUE,
         Sublegal = SublegalCPUE,
         Legal = LegalCPUE,
         Juvenile = JuvCPUE,
         Subadult = SubadultCPUE,
         Adult = AdultCPUE) %>%
  select(1:6, 11, 12) %>%
  left_join(.,depend, by = "Year")#%>%
  #gather("Lifestage", "CPUE", 3:8) 

E98 = crabdata %>% 
  select(1:2, 5:14) %>%
  filter(ProjID %in% "E98") %>%
  rename(Total = CPUE,
         Sublegal = SublegalCPUE,
         Legal = LegalCPUE,
         Juvenile = JuvCPUE,
         Subadult = SubadultCPUE,
         Adult = AdultCPUE) %>%
  select(1:6, 11, 12) %>%
  left_join(.,depend, by = "Year")

```

```{r Figure 1 (Landings ~ Harbor Trawl Regressions), echo=FALSE, message=FALSE, warning=FALSE,dpi=600, fig.cap="Ordinary Least Squares (OLS) regression of Charleston Harbor watershed (Ashley River, Cooper River, Wando River and Charleston Harbor) total landings (dependent variable) in bushels by CRMS Harbor Trawl abundance CPUEs (independent variables).  Mean annual subadult CPUEs (>59mm & <127mm carapace width) are lagged 1 year, and mean annual juvenile CPUEs are lagged 2 years.", fig.width=10,fig.height=11}


#Landings ~ Total
formulaB90_T = lm(B90$LandingsCPUE ~ B90$MatureFemale + lag(B90$Subadult))
summary(formulaB90_T)
B90TotalLandingsPlot = ggplot(aes(LandingsCPUE, MatureFemale+lag(Subadult)), data = B90) +
  ggtitle("Charleston Harbor Landings  \nby Harbor Trawl CPUE") +
  geom_point() +
  stat_poly_eq(aes(label = paste(..rr.label..)), 
               label.x.npc = "left", label.y.npc = 0.93,
               formula = formulaB90_T,rr.digits = 4,  parse = TRUE, size = 4) +
  stat_fit_glance(method = "lm", method.args = list(formula = formulaB90_T),
                  label.x = "left",
                  label.y = "top",
                  aes(label = paste("italic(P)*\"-value = \"*", 
                                    signif(..p.value.., digits = 4), sep = "")),
                  parse = TRUE) +
  geom_smooth(method = 'lm', se=FALSE, color="black") +
  labs(y=expression(Landings~CPUE~year^{-1}),
       x=expression(Blue~crab~trawl^{-1}))
B90TotalLandingsPlot

```







