---
title: "Dredge Table Attempt"
output:
  pdf_document: default
  word_document: default
classoption: landscape
geometry: margin=0.5cm
---

```{r setup, include=FALSE, echo=FALSE}
library(dplyr)
library(tidyr)
library(ggplot2)
library(PerformanceAnalytics)
library(MuMIn)
library(MASS)
library(knitr)
library(kableExtra)

# Read in data ------------------------------------------------------------

crab <- read.csv("CH1_T38Dredge.csv", stringsAsFactors = FALSE)
#crab is the unprepared for dredge original data
#Only those variables that have a predictive relationship
T38dredge <- filter(crab, Year > 1981) %>%
  dplyr::select(2, 3, 4, 9, 10, 12, 15, 16, 19, 21, 22, 24, 25, 27, 28, 30)
```

```{r Dredge Table, echo=FALSE, message=FALSE, warning=FALSE,dpi=600}
T38_lm <- lm(CPUE ~ ., data = T38dredge, na.action = "na.fail")
T38RelDredge <- dredge(T38_lm)
dt <- subset(T38RelDredge, delta < 5.5)
kable(dt) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"), font_size = 4)

```